[package]
name = "tests_fixtures"
version = "0.0.0"
edition = "2021"

[dependencies]
api_crypto = { path = "../../libparsec/crates/api_crypto" }
parsec_api_protocol = { path = "../parsec_api_protocol" }
api_types = { path = "../../libparsec/crates/api_types" }
parsec_client_types = { path = "../parsec_client_types" }

rstest = "0.13.0"
hex-literal = "0.3.3"
chrono = "0.4.19"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
