[package]
name = "tests_fixtures"
version = "0.0.0"
edition = "2021"

[dependencies]
parsec_api_crypto = { path = "../parsec_api_crypto" }
parsec_api_protocol = { path = "../parsec_api_protocol" }
parsec_api_types = { path = "../parsec_api_types" }
parsec_client_types = { path = "../parsec_client_types" }

rstest = "0.12.0"
hex-literal = "0.3.3"
chrono = "0.4.19"
