[package]
name = "libparsec_bindings_jni"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
libparsec_bindings_common = { path = "../../../common" }
lazy_static = "1.4.0"
jni = "0.20.0"
log = "0.4.14"
android_logger = "0.11"
