version: '2'
services:
  parsec:
    build:
      context: .
      dockerfile: packaging/docker/Dockerfile
    environment:
      - PARSEC_HOST=0.0.0.0
      - PARSEC_DB=postgresql://parsec@postgres/parsec?password=DBPASS  # Change db password for prod
      - PARSEC_BLOCKSTORE=POSTGRESQL  # This is a demo...
      - PARSEC_LOG_LEVEL=INFO
      - PARSEC_ADMINISTRATION_TOKEN=s3cr3t  # Change for prod
      - PARSEC_DB_FIRST_TRIES_NUMBER=20
      - PARSEC_DB_FIRST_TRIES_SLEEP=1
    ports:
      - 6777:6777
    depends_on:
      - "postgres"

  postgres:
    image: "postgres"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=parsec
      - POSTGRES_PASSWORD=DBPASS  # Change for prod
      - POSTGRES_DB=parsec


volumes:
  postgres-data:
