[package]
name = "parsec_api_types"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/tests.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { version = "0.0.0", path = "../parsec_api_crypto" }

lazy_static = "1.4.0"
serde = {version = "1.0.127", features = ["derive"]}
serde_with = "1.11.0"
serde_repr = "0.1.7"
rmp-serde = "1.0.0"
serde_bytes = {version = "0.11.5"}
chrono = {version = "0.4.19", features = ["serde"]}
# By default uuid crate uses `getrandom` directly instead of `rand`, however
# the latter is much faster (see. https://github.com/uuid-rs/uuid/pull/545,
# tl;dr: `rand` uses `getrandom` as seed then applies a fast chacha algo on it)
# Hence `fast-rng` feature which enables the use of `rand`.
uuid = {version = "1.0.0-alpha.1", features = ["serde", "v4", "fast-rng"]}
data-encoding = "2.3.2"
url = "2.2.2"
percent-encoding = "2.1.0"
regex = "1.5.4"
unicode-normalization = "0.1.19"
paste = "1.0.5"
flate2 = "1.0.22"
rand = "0.8.4"
thiserror = "1.0.30"

[dev-dependencies]
tests_fixtures = { version = "0.0.0", path = "../tests_fixtures" }
pretty_assertions = "1.0.0"
serde_test = "1.0.130"
hex-literal = "0.3.3"
rstest = "0.12.0"
rstest_reuse = "0.1.3"
serde_json = "1.0.59"

[features]
js = ["uuid/js"]
default = ["uuid/fast-rng"]
