[package]
name = "parsec_client_types"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/tests.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { version = "0.0.0", path = "../parsec_api_crypto" }
parsec_api_types = { version = "0.0.0", path = "../parsec_api_types" }

flate2 = "1.0.22"
serde = {version = "1.0.127", features = ["derive"]}
serde_with = "1.11.0"
serde_repr = "0.1.7"
rmp-serde = "1.0.0"
serde_bytes = {version = "0.11.5"}
sha2 = {version="0.10.0"}
paste = "1.0.5"
fancy-regex = "0.8.0"

[dev-dependencies]
tests_fixtures = { version = "0.0.0", path = "../tests_fixtures" }
pretty_assertions = "1.0.0"
serde_test = "1.0.130"
hex-literal = "0.3.3"
rstest = "0.12.0"
rstest_reuse = "0.1.3"
