---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
dictionaryDefinitions:
  - name: custom-words
    path: ./custom-words.txt
    scope: workspace
    addWords: true
  - name: names
    path: ./names.txt
    scope: workspace
    addWords: true
  # Not all french word are present in the `fr-fr` dictionary.
  - name: french-words
    path: ./french-words.txt
    addWords: true
  # `filetypes` is missing some file types
  - name: custom-ext
    path: ./custom-ext.txt
    addWords: true
  - name: jinja
    path: ./jinja.txt
    addWords: true
dictionaries:
  - en_us
  - en-gb
  - fr-fr
  - french-words
  - lorem-ipsum
  - misc
  - softwareTerms
  - networking-terms
  - python
  - python-common
  - rust
  - cpp
  - cpp-refined
  - filetypes
  - bash
  - shell
  - custom-words
  - filetypes
  - custom-ext
  - names
  - typescript
  - sql
  - win32
  - jinja
words:
  - libparsec
  - schemafile
  - intlify
  - htmlcov
  - Swatinem
ignoreWords:
  - ABCDEFGHJKLMNPQRSTUVWXYZ
  - Aaaaaand
  - AIAA
  - ApiV
  - Assss
  - devel
  - Crefreshiconhandler
  - Cwindowsiconhandler
  - DWXJ
  - EFGH
  - HRSW
  - JKLM
  - KBWM
  - NNWQ
  - NPQR
  - PQRSTUVWXYZHIJKLMNO
  - QPGW
  - QPIM
  - QWIPQs
  - QYJW
  - SPFYHIZLEL
  - SPIHB
  - SYMED
  - VFKA
  - VQLP
  - WPFF
  - XBAO
  - XPCMTSEN
  - YVPZ
  - ZGIQ
  - ZOXKGGIMTY
  - abcefg
  - ackup
  - csdef
  - dbmdl
  - dbproj
  - dksjdskdjs
  - ebug
  - elease
  - eleases
  - esult
  - iobj
  - ipch
  - ipdb
  - jmconfig
  - mnpcod
  - ntvs
  - nunit
  - nupkg
  - nvuser
  - paket
  - pidb
  - psess
  - rsuser
  - snupkg
  - splitn
  - tqdm
  - Ssjfq
cache:
  cacheFormat: universal
  cacheStrategy: metadata
  useCache: true
useGitignore: true
allowCompoundWords: false
ignorePaths:
  # Cspell seems to match against the absolute path, so must always start with `**/` :(
  - "**/bindings/web/src/meths.rs"
  - "**/bindings/electron/src/meths.rs"
  - "**/*.svg"
  - "**/*.excalidraw"
  - "**/default_pattern.ignore"
  - "**/docs/figures/*.svg"
  - "**/windows-icon-handler/**/*.vcxproj"
  - "**/windows-icon-handler/**/*.vcxproj.filters"
  - "**/gradle.lockfile"
  - "**/buildscript-gradle.lockfile"
  - "**/gradle/verification-metadata.xml"
  - "**/*.icns"
  - "**/.git"
  - "**/*.der"
import:
  - "@cspell/dict-fr-fr/cspell-ext.json"
  - "@cspell/dict-fr-reforme/cspell-ext.json"
  - "@cspell/dict-bash/cspell-ext.json"
  - "@cspell/dict-shell/cspell-ext.json"
  - "@cspell/dict-win32/cspell-ext.json"
