[package]
name = "libparsec_client_types"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparsec_crypto = { path = "../crypto" }
libparsec_types = { path = "../types" }
serialization_format = { path = "../serialization_format" }

flate2 = "1.0.24"
serde = { version = "1.0.145", features = ["derive"] }
serde_with = "2.0.0"
serde_repr = "0.1.9"
rmp-serde = "1.0.0"
serde_bytes = "0.11.7"
sha2 = "0.10.6"
paste = "1.0.9"
fancy-regex = "0.10.0"
thiserror = "1.0.34"

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }
pretty_assertions = "1.3.0"
serde_test = "1.0.144"
hex-literal = "0.3.3"
rstest = "0.15.0"
rstest_reuse = "0.4.0"
