[package]
name = "libparsec_serialization_format"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"

[lib]
proc-macro = true

[dependencies]
itertools = "0.10.5"
miniserde = "0.1.30"
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.13", features = ["extra-traits"] }

[dev-dependencies]
libparsec_types = { path = "../types" }
rstest = "0.17.0"
pretty_assertions = "1.3.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.2.0"
rmp-serde = "1.1.1"
