[package]
name = "serialization_format"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.65"
miniserde = "0.1.27"
proc-macro2 = "1.0.43"
quote = "1.0.21"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
syn = "1.0.99"

[dev-dependencies]
rstest = "0.15.0"
pretty_assertions = "1.3.0"
