[package]
name = "serialization_format"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.65"
itertools = "0.10.5"
miniserde = "0.1.27"
proc-macro2 = "1.0.47"
quote = "1.0.21"
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.89"
syn = { version = "1.0.99", features = ["full", "extra-traits", "test"] }

[dev-dependencies]
rstest = "0.15.0"
pretty_assertions = "1.3.0"
