[package]
name = "libparsec_serialization_format"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
miniserde = "0.1.27"
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = { version = "1.0.105", features = ["extra-traits"] }

[dev-dependencies]
libparsec_protocol = { path = "../protocol" }
libparsec_types = { path = "../types" }
rstest = "0.16.0"
pretty_assertions = "1.3.0"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.1.0"
rmp-serde = "1.1.1"
