[package]
name = "libparsec_tests_fixtures"
version = "0.0.0"
edition = "2021"

[dependencies]
libparsec_types = { path = "../types", features = [ "test-fixtures" ] }
libparsec_tests_macros = { path = "../tests_macros" }
libparsec_testbed = { path = "../testbed" }
# Enable testbed support in crates here
libparsec_client_connection = { path = "../client_connection", features = [ "test-with-testbed" ] }
libparsec_platform_device_loader = { path = "../platform_device_loader", features = [ "test-with-testbed" ] }
libparsec_platform_storage = { path = "../platform_storage", features = [ "test-with-testbed" ] }
libparsec_platform_storage2 = { path = "../platform_storage2", features = [ "test-with-testbed" ] }

env_logger = "0.10.0"
log = "0.4.17"
rstest = "0.17.0"
hex-literal = "0.4.1"
uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }
lazy_static = "1.4.0"
pretty_assertions = "1.3.0"

# TODO: Currently `parsec_test` doesn't support web
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.28.0", features = ["fs", "sync"] }

# No dev-dependencies: this crate is itself only used in other crates' own dev-dependencies
