[package]
name = "tests_fixtures"
version = "0.0.0"
edition = "2021"

[dependencies]
libparsec_crypto = { path = "../crypto" }
libparsec_types = { path = "../types" }
libparsec_client_types = { path = "../client_types" }

rstest = "0.16.0"
hex-literal = "0.3.3"
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }
