[package]
name = "tests_fixtures"
version = "0.0.0"
edition = "2021"

[dependencies]
libparsec_crypto = { path = "../crypto" }
libparsec_protocol = { path = "../protocol" }
libparsec_types = { path = "../types" }
libparsec_client_types = { path = "../client_types" }

rstest = "0.13.0"
hex-literal = "0.3.3"
chrono = "0.4.19"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
remove_dir_all = "0.7.0"
