[package]
name = "parsec_cli"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { path = "../../crates/parsec_api_crypto" }

diesel = { version = "2.0.0-rc.0", features = ["sqlite"], git = "https://github.com/diesel-rs/diesel" }
clap = { version = "3.1.18", features = ["derive"] }
rmp-serde = "1.0.0"
serde = { version = "1.0.127", features = ["derive"] }
