[package]
name = "libparsec_testbed"
version = "0.0.0"
edition = "2021"

[dependencies]
libparsec_crypto = { path = "../crypto" }
libparsec_types = { path = "../types" }

hex-literal = "0.3.3"
crc32fast = "1.3.2"
serde = { version = "1.0.147", features = ["derive"] }
rmp-serde = "1.1.1"
lazy_static = "1.4.0"
reqwest = "0.11.16"

[dev-dependencies]
libparsec_tests_fixtures = { path = "../tests_fixtures" }
