[package]
name = "libparsec_core_fs"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
test-utils = []

[dependencies]
libparsec_client_connection = { path = "../client_connection" }
libparsec_client_types = { path = "../client_types" }
libparsec_core = { path = "../core" }
libparsec_crypto = { path = "../crypto" }
libparsec_protocol = { path = "../protocol" }
libparsec_types = { path = "../types" }

# Disable Diesel's default feature to remove `32-column-tables` which slowdown compilation
# quiet a lot (Diesel crate compilation on my machine: 19s with vs 8s without).
# Note this is fine as long as we use tables with at most 16 columns.
diesel = { version = "2.0.3", default-features = false }
log = "0.4.17"
regex = "1.7.2"
thiserror = "1.0.37"
uuid = { version = "1.2.2", features = ["v4", "fast-rng"] }
lazy_static = "1.4.0"
libparsec_platform_local_db = { path = "../platform_local_db" }
async-trait = "0.1.61"
libparsec_platform_async = { path = "../platform_async" }

[dev-dependencies]
libparsec_tests_fixtures = { path = "../tests_fixtures" }

rstest = "0.16.0"
tokio = { version = "1.24.1", features = ["macros"]}
test-log = "0.2.11"
env_logger = "0.10.0"
