[package]
name = "libparsec_core_fs"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparsec_crypto = { path = "../crypto" }
libparsec_types = { path = "../types" }
libparsec_client_types = { path = "../client_types" }

diesel = { version = "2.0.2", features = ["sqlite", "r2d2"] }
libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }
regex = "1.6.0"
thiserror = "1.0.37"
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }

rstest = "0.15.0"
