[package]
name = "libparsec_core_fs"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# We depend on platform storage's `test-utils` to implement our own test utils
# (e.g. `drop_deferred_commit_manifest`)
test-utils = [
    "libparsec_platform_storage/test-utils"
]

[dependencies]
libparsec_client_connection = { path = "../client_connection" }
libparsec_core = { path = "../core" }
libparsec_crypto = { path = "../crypto" }
libparsec_protocol = { path = "../protocol" }
libparsec_types = { path = "../types" }
libparsec_platform_async = { path = "../platform_async" }
libparsec_platform_storage = { path = "../platform_storage" }

log = "0.4.17"
regex = "1.7.3"
thiserror = "1.0.40"
lazy_static = "1.4.0"
async-trait = "0.1.61"

[dev-dependencies]
libparsec_tests_fixtures = { path = "../tests_fixtures" }
libparsec_testbed = { path = "../testbed" }
libparsec_platform_storage = { path = "../platform_storage", features = ["test-utils"] }

tokio = { version = "1.27.0", features = ["macros"]}
