[package]
name = "libparsec_core_fs"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparsec_crypto = { path = "../crypto" }
libparsec_types = { path = "../types" }
libparsec_client_types = { path = "../client_types" }

# Disable Diesel's default feature to remove `32-column-tables` which slowdown compilation
# quiet a lot (Diesel crate compilation on my machine: 19s with vs 8s without).
# Note this is fine as long as we use tables with at most 16 columns.
diesel = { version = "2.0.2", features = ["sqlite"], default-features = false }
libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }
regex = "1.6.0"
thiserror = "1.0.37"
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }
lazy_static = "1.4.0"
local_db = { path = "../platform_local_db", package = "platform_local_db"}
async-trait = "0.1.61"
platform_async = { path = "../platform_async", package = "libparsec_platform_async" }

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }

rstest = "0.16.0"
tokio = { version = "1.24.1", features = ["macros"]}
