[package]
name = "libparsec_core_fs"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { path = "../../../crates/parsec_api_crypto" }
parsec_api_types = { path = "../../../crates/parsec_api_types" }
parsec_client_types = { path = "../../../crates/parsec_client_types" }

diesel = { version = "2.0.0-rc.0", features = ["sqlite", "r2d2"] }
fancy-regex = "0.10.0"
thiserror = "1.0.30"
uuid = { version = "1.0.0-alpha.1", features = ["v4", "fast-rng"] }

[dev-dependencies]
tests_fixtures = { path = "../../../crates/tests_fixtures" }

rstest = "0.12.0"
