[package]
name = "platform_native"
version = "0.0.0"
edition = "2021"

[[test]]
name = "integration"
path = "tests/mod.rs"

[dependencies]
http = "0.2.8"
futures = "0.3.21"
dotenv = "0.15.0"
smol = "1.2.5"
async-std = "1.12.0"
async-tungstenite = { version = "0.17.1", features = ["async-std-runtime"] }

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }
api_protocol = { path = "../api_protocol" }
api_types = { path = "../api_types" }

rstest = "0.13.0"
