appId: com.scille.parsec-v3-alpha

directories:
  buildResources: assets

files:
  - assets/**/*
  - build/**/*
  - app/**/*

publish:
  provider: github

nsis:
  allowElevation: true
  oneClick: false
  allowToChangeInstallationDirectory: true

win:
  target: nsis

mac:
  category: your.app.category.type
  target: dmg

linux:
  synopsis: Secure cloud framework
  description: >-
    Parsec is an open-source cloud-based application that allow simple yet
    cryptographically secure file hosting.
  category: Office Network FileTransfer FileSystem Security
  desktop:
    MimeType: x-scheme-handler/parsec3;

snap:
  base: core22
  # Currently the snap is not ready for production
  grade: devel
  allowNativeWayland: true
  stagePackages:
    - default
    - fuse3

extends: null
