[package]
name = "parsec_api_protocol"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/tests.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { version = "0.0.0", path = "../parsec_api_crypto" }
parsec_api_types = { version = "0.0.0", path = "../parsec_api_types" }

chrono = {version = "0.4.19", features = ["serde"]}
paste = "1.0.5"
serde = {version = "1.0.127", features = ["derive"]}
serde_with = "1.11.0"
