[package]
name = "parsec_api_protocol"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/tests.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec_api_crypto = { path = "../parsec_api_crypto" }
parsec_api_types = { path = "../parsec_api_types" }
parsec_serialization_format = { path = "../parsec_serialization_format" }

paste = "1.0.5"
rand = "0.8.5"
rmp-serde = "1.1.0"
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.59"
serde_with = "1.11.0"
thiserror = "1.0.30"

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }
hex-literal = "0.3.3"
rstest = "0.12.0"
serde_json = "1.0.0"

[features]
test = []
