[package]
name = "libparsec_core"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparsec_client_types = { path = "../client_types" }
libparsec_crypto = { path = "../crypto" }
libparsec_protocol = { path = "../protocol" }
libparsec_types = { path = "../types" }

rmp-serde = "1.1.1"
serde = { version = "1.0.145", features = ["derive"] }
serde_with = "2.0.1"
thiserror = "1.0.37"

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }

rstest = "0.15.0"
chrono = "0.4.22"
