[package]
name = "libparsec_core"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use-rustcrypto"]
use-rustcrypto = ["libparsec_crypto/use-rustcrypto"]
use-sodiumoxide = ["libparsec_crypto/use-sodiumoxide"]

[dependencies]
libparsec_client_types = { path = "../client_types", default-features = false }
libparsec_crypto = { path = "../crypto", default-features = false }
libparsec_platform_async = { path = "../platform_async" }
libparsec_platform_device_loader = { path = "../platform_device_loader" }
libparsec_protocol = { path = "../protocol", default-features = false }
libparsec_types = { path = "../types", default-features = false }

once_cell = "1.17.0"
rmp-serde = "1.1.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.1.0"
thiserror = "1.0.37"

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }

rstest = "0.16.0"
