[package]
name = "libparsec_protocol"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libparsec_types = { path = "../types" }
libparsec_serialization_format = { path = "../serialization_format" }

paste = "1.0.12"
rand = "0.8.5"
rmp-serde = "1.1.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.2.0"
thiserror = "1.0.40"
futures = "0.3.28"

[dev-dependencies]
libparsec_tests_fixtures = { path = "../tests_fixtures" }
hex-literal = "0.3.3"
serde_json = "1.0.91"

[build-dependencies]
glob = "0.3.0"
