[package]
name = "libparsec_protocol"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"
autotests = false

[[test]]
name = "integration"
path = "tests/mod.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use-rustcrypto"]
use-rustcrypto = ["libparsec_crypto/use-rustcrypto"]
use-sodiumoxide = ["libparsec_crypto/use-sodiumoxide"]
test = []

[dependencies]
libparsec_crypto = { path = "../crypto", default-features = false }
libparsec_types = { path = "../types", default-features = false }
libparsec_serialization_format = { path = "../serialization_format" }

paste = "1.0.9"
rand = "0.8.5"
rmp-serde = "1.1.1"
serde = { version = "1.0.147", features = ["derive"] }
serde_with = "2.1.0"
thiserror = "1.0.37"
futures = "0.3.24"

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }
hex-literal = "0.3.3"
rstest = "0.16.0"
serde_json = "1.0.89"

[build-dependencies]
glob = "0.3.0"
