[tool.poetry]
name = "parsec-docs"
version = "0.0.0"
description = "Parsec documentation"
authors = ["Scille SAS <contact@scille.fr>"]
license = "BUSL-1.1"
packages = [
    { include = "conf.py" }
]

[tool.poetry.dependencies]
python = "^3.9.10"
sphinx = "<8.0.0"
sphinx-intl = "^2.1.0"
sphinx-rtd-theme = "^2.0.0"
sphinx-copybutton = "^0.5.2"
docutils = "0.20.1"
poutils = "^0.15.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
