[tool.poetry]
name = "parsec-docs"
version = "0.0.0"
description = "Parsec documentation"
authors = ["Scille SAS <contact@scille.fr>"]
license = "BUSL-1.1"
packages = [{ include = "conf.py" }]

[tool.poetry.dependencies]
python = "^3.12.0"
sphinx = "<9.0.0"
sphinx-copybutton = "^0.5.2"
sphinx-intl = "^2.3.1"
sphinx-rtd-theme = "^3.0.2"
sphinx-tabs = "^3.4.7"
docutils = "0.21.2"
powrap = "^1.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
