[package]
name = "libparsec_platform_async"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.10.14"
# futures is used for its macros `select_all` and `join_all`
futures = "0.3.24"

[dev-dependencies]
log = "0.4.17"
# `std::time::Instant` is not available for wasm32, crate `instant` provides a
# fallback based on `window.performance.now()`
instant = "0.1.12"
# Used for `futures_lite::future::or` and don't require `Unpin`
futures-lite = "1.12.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.82"
wasm-bindgen-futures = "0.4.31"
# Window feature is require for `Timer`.
web-sys = { version = "0.3.58", features = ["Window"] }
js-sys = "0.3.58"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.31"
# Used for binding `log` with `console.log*`
console_log = "0.2.0"
instant = { version = "0.1.12", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.21.0", features = ["rt", "time", "sync", "macros"] }

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.21.0", features = ["full"] }
simple_logger = "2.3.0"
