[package]
name = "libparsec_tests_macros"
version = "0.0.0"
edition = "2021"
license = " BUSL-1.1"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = { version = "2.0.13" }
