[package]
name = "libparsec_platform_device_loader"
version = "0.0.0"
edition = "2021"

[features]
test-testbed-support = [
    "libparsec_testbed"
]

[dependencies]
libparsec_types = { path = "../types" }
libparsec_client_types = { path = "../client_types" }
libparsec_crypto = { path = "../crypto" }
libparsec_testbed = { path = "../testbed", optional = true }

serde_json = "1.0.91"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.60", features = ["Window", "Storage"] }

[dev-dependencies]
# Note `libparsec_tests_fixtures` enables our `test-testbed-support` feature
libparsec_tests_fixtures = { path = "../tests_fixtures" }

hex-literal = "0.3.3"
tokio = "1.25.0"
rstest = "0.16.0"

[[test]]
name = "integration"
path = "tests/mod.rs"
