[package]
name = "libparsec_platform_device_loader"
version = "0.0.0"
edition = "2021"

[dependencies]
libparsec_client_types = { path = "../client_types" }
libparsec_crypto = { path = "../crypto" }

serde_json = "1.0.91"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.60", features = ["Window", "Storage"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.24.1", features = ["fs"]}

[dev-dependencies]
tests_fixtures = { path = "../tests_fixtures" }

hex-literal = "0.3.3"
tokio = "1.24.1"
rstest = "0.16.0"

[[test]]
name = "integration"
path = "tests/mod.rs"
