[package]
name = "libparsec_platform_device_loader"
version = "0.0.0"
edition = "2021"

[features]
test-with-testbed = [
    "libparsec_testbed"
]

[dependencies]
libparsec_types = { path = "../types" }
libparsec_crypto = { path = "../crypto" }
libparsec_testbed = { path = "../testbed", optional = true }
keyring = "2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3.60", features = ["Window", "Storage"] }
serde_json = "1.0.91"

[dev-dependencies]
# Note `libparsec_tests_fixtures` enables our `test-with-testbed` feature
libparsec_tests_fixtures = { path = "../tests_fixtures" }

hex-literal = "0.4.1"
tokio = "1.28.1"

[[test]]
name = "integration"
path = "tests/mod.rs"
