name: CI Docs

on:
  workflow_call:
  workflow_dispatch:

# We set `concurrency` to prevent having this workflow being run on code that is not up-to-date on a PR (a user make multiple push in a quick manner).
# But on the main branch, we don't want that behavior.
# Having the workflow run on each merge commit is something we would like, that could help us where a regression was made and missed by previous checks.
#
# For that we use `head_ref` that is only defined on `pull-request` and fallback to `run_id` (this is a counter, so it's value is unique between workflow call).
concurrency:
  group: ci-docs-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  poetry-version: 2.2.1
  # Convert sphinx warning into errors.
  SPHINXOPTS: --fail-on-warning --verbose

permissions:
  contents: read

jobs:
  docs:
    name: Build & Check documentations
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin v6.0.2
        with:
          sparse-checkout: |
            .github
            HISTORY.rst
            docs
        timeout-minutes: 2

      - uses: taiki-e/install-action@887bc4e03483810873d617344dd5189cd82e7b8b # pin v2.67.11
        with:
          tool: ripgrep

      - uses: ./.github/actions/setup-python-poetry
        id: setup-python
        with:
          poetry-version: ${{ env.poetry-version }}
          project-path: ./docs
        timeout-minutes: 10

      - name: Install gettext (required by powrap)
        run: |
          sudo apt-get install -y gettext
          gettext --version
        timeout-minutes: 5

      - name: Install docs deps
        run: |
          poetry env info
          poetry install
          poetry show
        timeout-minutes: 5

      - name: Update translation
        run: poetry run make --environment-overrides intl-fr
        timeout-minutes: 2

      - name: Wrap `*.po` files
        run: poetry run make --environment-overrides wrap
        timeout-minutes: 1

      - name: No fuzzy translation
        run: |
          ! rg '#, fuzzy' locale/
        timeout-minutes: 1

      - name: Check if `*.po` were modified
        shell: bash
        run: |
          if [ -n "$(git status --porcelain '*.po' | tee /dev/stderr)" ]; then
            # PO files were modified, the step fail
            exit 1
          else
            # NO PO files were modified, the step succeed
            exit 0
          fi

      - name: Build html documentation
        run: poetry run make --environment-overrides html
        timeout-minutes: 2
