name: linux-ci

on:
  pull_request:
  push:
    branches:
      - master

env:
  rust-version: 1.62.0
  python-version: "3.9"
  poetry-version: 1.1.13
  postgre-version: 12

jobs:
  linux-ci-rust:
    # Using ubuntu 20 for consistency with the python job
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin v3.0.2
      - uses: ./.github/actions/setup-rust
        with:
          version: ${{ env.rust-version }}
          cache-key: test&build

      - name: Build rust codebase
        run: |
          cargo build --workspace
          cargo test --workspace --no-run

      - name: Test rust codebase
        run: |
          cargo test --package libparsec_crypto --features use-sodiumoxide
          cargo test --package libparsec_crypto --features use-rustcrypto
          cargo test --workspace --features mock-time --exclude libparsec_crypto

  linux-ci-python:
    # Using ubuntu 20 in order to have postgresql-12 available as an APT package
    runs-on: ubuntu-20.04
    env:
      PYTEST_BASE_ARGS: >-
        --durations=10
        --side-effects-timeout=10
        -vv
        -x
    strategy:
      fail-fast: false
      matrix:
        binding: [ stable-binding, unstable-rust-binding ]
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin v3.0.2

      - name: Install APT packages
        # Only libfuse3 is available on ubuntu-20.04,
        # and `desktop-file-utils` provides `update-desktop-database` used by `tests/scripts/run_testenv.sh`
        # and a specific version of postgresql is used
        run: sudo apt-get -y install libfuse2 fuse desktop-file-utils postgresql-${{ env.postgre-version }}

      - uses: ./.github/actions/setup-rust
        with:
          version: ${{ env.rust-version }}
          cache-key: python

      - name: Install poetry
        run: |
          set -eux
          export POETRY_HOME="$HOME/.poetry"
          mkdir -p "$POETRY_HOME"
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py \
            | python - --version=${{ env.poetry-version }}
          echo "$POETRY_HOME/bin" >> "$GITHUB_PATH"

      - uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08  # pin v4.1.0
        with:
          python-version: ${{ env.python-version }}
          cache: poetry

      - name: Install python deps
        run: |
          set -e
          poetry install -E core -E backend
          poetry run maturin develop

      - name: Generate PyQT GUI data
        run: poetry run python misc/generate_pyqt.py

      - name: Install libparsec_python
        if: matrix.binding == 'unstable-rust-binding'
        run: poetry run pip install oxidation/libparsec_python

      - name: Basic tests
        run: poetry run pytest ${{ env.PYTEST_BASE_ARGS }} tests
        timeout-minutes: 3

      - name: Rust binding tests
        if: matrix.binding == 'unstable-rust-binding'
        run: poetry run pytest ${{ env.PYTEST_BASE_ARGS }} tests --runrust -m rust
        timeout-minutes: 3

      - name: Mountpoint tests
        run: poetry run pytest ${{ env.PYTEST_BASE_ARGS }} tests --runmountpoint --runslow -m mountpoint
        timeout-minutes: 10

      # Install the require package for testing Qt
      # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
      - name: Install APT deps for GUI testing
        run: >
          sudo apt-get install
          libxkbcommon-x11-0
          libxcb-icccm4
          libxcb-image0
          libxcb-keysyms1
          libxcb-randr0
          libxcb-render-util0
          libxcb-xinerama0
          libxcb-xfixes0
          x11-utils

      # Install Xvfb plugin to be started by pytest
      # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#id1
      - name: Install Xvfb pytest plugin
        run: poetry run pip install pytest-xvfb

      - name: GUI tests
        run: poetry run pytest ${{ env.PYTEST_BASE_ARGS }} tests --runmountpoint --runslow --rungui -m gui
        timeout-minutes: 10

      - name: PostgreSQL tests
        env:
          PGINSTALLATION: /usr/lib/postgresql/${{ env.postgre-version }}/bin
        run: poetry run pytest ${{ env.PYTEST_BASE_ARGS }} tests/backend tests/test_cli.py -k 'not test_shuffle_roles' --postgresql --runslow
        timeout-minutes: 10

      - name: Hypothesis tests
        run: poetry run pytest ${{ env.PYTEST_BASE_ARGS }} tests --runslow -m slow --numprocesses auto
        timeout-minutes: 20
