name: macos-ci

on:
  pull_request:
  push:
    branches:
      - master

env:
  rust-version: 1.62.0
  python-version: "3.9"
  poetry-version: 1.1.13

jobs:
  rust:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin v3.0.2
      - uses: ./.github/actions/setup-rust
        with:
          version: ${{ env.rust-version }}
          cache-key: test&build

      # Pyo3 need additional configuration on MacOS to be manually build
      # see https://pyo3.rs/master/building_and_distribution.html#macos
      - name: Configure cargo for pyo3
        run: |
          set -eux
          set -o pipefail
          mkdir -p .cargo
          cat << EOF | tee .cargo/config.toml
          [target.x86_64-apple-darwin]
          rustflags = [
            "-C", "link-arg=-undefined",
            "-C", "link-arg=dynamic_lookup",
          ]
          EOF

      - name: Build rust codebase
        run: |
          cargo build --workspace
          cargo test --workspace --no-run

      - name: Test rust codebase
        run: |
          cargo test --package libparsec_crypto --features use-sodiumoxide
          cargo test --package libparsec_crypto --features use-rustcrypto

          cargo test --workspace --features mock-time --exclude libparsec_crypto

  macos-ci-python:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin v3.0.2

      - name: Install macfuse
        run: brew install --cask macfuse

      - name: Install poetry
        run: |
          export POETRY_HOME="$HOME/.poetry"
          mkdir -p "$POETRY_HOME"
          curl -sSL https://install.python-poetry.org \
            | python3 - --version=${{ env.poetry-version }}
          echo "$POETRY_HOME/bin" >> "$GITHUB_PATH"

      - uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08  # pin v4.0.0
        with:
          python-version: ${{ env.python-version }}
          cache: poetry

      - name: Install python deps
        run: poetry install -E core -E backend

      - name: Generate PyQT GUI data
        run: poetry run python misc/generate_pyqt.py

      - name: Test python
        run: >
          poetry run pytest
          -n auto
          -vv
          -x
          --log-level=DEBUG
          --durations=10
          --side-effects-timeout=10
