name: macos-ci

on:
  pull_request:
  push:
    branches:
      - master

env:
  rust-version: 1.62.0
  python-version: "3.9"
  poetry-version: 1.2.0b3

jobs:
  macos-ci-python:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # pin v3.0.2

      - name: Install macfuse
        run: brew install --cask macfuse

      - name: Install poetry
        run: |
          set -eux
          export POETRY_HOME="$HOME/.poetry"
          mkdir -p "$POETRY_HOME"
          curl -sSL https://install.python-poetry.org | python3 - --version=${{ env.poetry-version }}
          echo "$POETRY_HOME/bin" >> "$GITHUB_PATH"

      - uses: ./.github/actions/setup-rust
        with:
          version: ${{ env.rust-version }}
          cache-key: python

      - uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08  # pin v4.1.0
        id: setup-python
        with:
          python-version: ${{ env.python-version }}
          cache: poetry

      - name: Configure python path for poetry
        run: poetry env use ${{ steps.setup-python.outputs.python-path }}

      - name: Install python deps
        run: poetry install -E core -E backend

      - name: Test python
        run: >
          poetry run pytest
          -n auto
          -vv
          -x
          --log-level=DEBUG
          --durations=10
          --side-effects-timeout=10
