name: test-rust-ci

on:
  pull_request:
    paths:
      - "**"
      - "!oxidation/**.rs"
      - "!oxidation/**.toml"
      - "!Cargo.toml"
      - "!Cargo.lock"
      - "!src/**.rs"
      - "!.github/workflows/test-rust-ci.yml"
      - "!.github/actions/setup-rust/**"

jobs:
  testing-rust-matrix:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "No build required for RUST"
