name: test-python-ci

on:
  pull_request:
    paths:
      - .github/workflows/mock-test-python-ci.yml
      - "!parsec/**"
      - "!tests/**"
      - "!src/**.rs"
      - "!pyproject.toml"
      - "!poetry.lock"
      - "!.github/workflows/test-python-ci.yml"
      - "!.github/actions/setup-python-poetry/**"
      - "!.github/actions/setup-rust/**"

jobs:
  test-python-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No build required for PYTHON"
